services:
  web:
    image: web
    container_name: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
        - web.database
        - web.keycloak
    environment:
      - ConnectionStrings__Poster_DB=Host=web.database;Port=5432;Database=Poster_DB;Username=postgres;Password=postgres
      - Keycloak__Authority=https://keycloak:8180/auth/realms/PosterRealm
      - Keycloak__Audience=PosterAPI
    
  web.database:
    image: postgres:latest
    container_name: web.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Poster_DB
    volumes:
      - ./.containers/poster_db:/var/lib/postgresql/data
    ports:
        - "5432:5432"
          
  web.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: web.keycloak
    environment:
      # initial admin user
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak.db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command: start --hostname-strict=false --http-enabled=true
    depends_on:
      - keycloak.db
    ports:
      - "8180:8080"           # Keycloak Admin Console at http://localhost:8180
        
  keycloak.db:
    image: postgres:latest
    container_name: keycloak.db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ./.containers/keycloak_postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"